### ISSUE TITLE
Problem creating even file for Contraception discontinuation rates

### ISSUE THREAD

**Issue by awazir** [DHSProgram/DHS-Indicators-Stata#2]
Dear Author
It is a great help for the programmers who are currently working on DHS data. I am working with Pakistan latest PDHS 2017-18 data, to calculate the contraception discontinuation rates. When I have used the "IR" to create an event file in STATA, the following error is prompted. Please guide me how to solve this. 
 
 local vcal_len = strlen(vcal_`col1'[1])
vcal_ ambiguous abbreviation

**Comment by awazir** [comment]
Chap07_FP/FP_EVENTS.do

**Comment by shireen122** [comment]
Dear Asif,

Great to hear you are using the DHS Stata code on Github.

For the line you mentioned to work you would have to run the line
_local col1 1_ 
which was at the top of the do file (line 33). 

Perhaps you are running the code line by line, which may not work. Please run the entire do file at once so that the locals can work. In this case the local col1 is set to 1 so when you run the line 
_local vcal_len = strlen(vcal_`col1'[1])_
this really means
_local vcal_len = strlen(vcal_1[1])_

You received the error because Stata could not find the local `col1’. 

Hope this helps.

Best,

Shireen
